### ISSUE TITLE
Cannot spawns a process called "rustc" on Windows

### ISSUE THREAD

**Issue by alexcrichton** [Diggsey/multirust-rs#13]
When using multirust on Windows it looks like invocations along the lines of `Command::new("rustc")` will fail because there's no binary called `rustc.exe` on the system (maybe the shell only runs batch files?)

**Comment by Diggsey** [comment]
Yes, unfortunately this is the unforeseen downside of using batch files as proxies. Command is essentially a wrapper around `CreateProcess`, which only looks for `.exe` files unless you specify a full path.

I have several options, each of which have their own downsides:
1) Use batch files, have this problem
2) Use symlinks, require admin privileges to install multirust
3) Use copies of the multirust binary, the multirust binary is pretty big to duplicate a bunch of times
4) Use stub executables, have to create them somehow...

Currently it looks like (2) with a fallback to (3) if it can't get admin permissions might be the best option.

**Comment by Diggsey** [comment]
This should be fixed now: it uses hardlinks on windows and symlinks elsewhere, instead of batch/shell scripts.

**Comment by alexcrichton** [comment]
Hurray! Thanks!
