### ISSUE TITLE
open_browser broken on linux

### ISSUE THREAD

**Issue by crumblingstatue** [Diggsey/multirust-rs#17]
The not(windows) implementation of open_browser uses `command` to see whether a command exists, but `command` is a shell-builtin (at least in bash), so it doesn't work when invoked through `process::Command`.

How about instead using the `which` command?

**Comment by crumblingstatue** [comment]
To put it in context, this renders `multirust doc` unusable, which is a feature I often used in the shell version.

**Comment by Diggsey** [comment]
Thanks for reporting this: it's now fixed and new binaries have been uploaded.
