### ISSUE TITLE
Light fonts on white terminal hard to see

### ISSUE THREAD

**Issue by alexcrichton** [Diggsey/multirust-rs#22]
![https://i.imgur.com/70fx6A1.png](https://i.imgur.com/70fx6A1.png)

It's tough for me to read the "beta"/"stable"/"nightly" tags in the lower left

**Comment by Diggsey** [comment]
Blargh, `term` doesn't seem to provide an API for getting the background colour. I suppose I could use blue or something... Is there some recipe for getting easy to read term output regardless of the user preferences, that I'm unaware of?

**Comment by alexcrichton** [comment]
Nah not that I know of unfortunately, I always thought that "light" would auto-translate to something dark on light backgrounds (e.g. my terminal would be smarter)...

**Comment by Diggsey** [comment]
For now I just use a black background whenever using white text, so it should at least be readable.
