### ISSUE TITLE
OSX binaries don't run on older machines

### ISSUE THREAD

**Issue by alexcrichton** [Diggsey/multirust-rs#24]
Like with https://github.com/Diggsey/multirust-rs/issues/23, building for OSX can be nontrivial sometimes to ensure that something works on older machines. I *think* that OSX doesn't need the same "CentOS 5 craziness" that Linux needs, but rather it can just set the `MACOSX_DEPLOYMENT_TARGET` environment variable to "10.7". To the best of my knowledge, that will instruct the linker to "do the old things" which I think is the only point of incompatibility.

"Thankfully" the OpenSSL OSX has and depends on is basically locked at 0.9.8, so no need to worry about that in this case!

**Comment by alexcrichton** [comment]
Hurray! #25 did the trick.

**Comment by Diggsey** [comment]
:+1:
