### ISSUE TITLE
multirust self update panics.

### ISSUE THREAD

**Issue by norcalli** [Diggsey/multirust-rs#26]
After running self update, I get a panic:

     ❯❯❯ multirust self update
    downloading file from: 'https://github.com/Diggsey/multirust-rs-binaries/raw/master/x86_64-apple-darwin/multirust-rs.sha256'
    thread '<main>' panicked at 'assertion failed: self.is_char_boundary(new_len)', ../src/libcollections/string.rs:597

**Comment by Diggsey** [comment]
The osx machines now correctly generate the sha256 checksums.
