### ISSUE TITLE
Can't install toolchains

### ISSUE THREAD

**Issue by alexcrichton** [Diggsey/multirust-rs#3]
I installed the 64-bit GNU installer and ran `multirust update nightly` and was met with:

```
extracting ...
tar (child): Cannot connect to C: resolve failed

gzip: stdin: unexpected end of file
tar: Child status returned 128
tar: Error is not recoverable: exiting now
error: command 'tar' terminated with exit code: 2
```

Might I recommend [flate2](https://crates.io/crates/flate2) + [tar](https://crates.io/crates/tar) for extracting tarballs? This is what Cargo uses and it seems to work out pretty well! (also removes a dep on a local `tar` command).

**Comment by Diggsey** [comment]
I assume when you say "64-bit GNU installer", you mean the linux version?
This shouldn't be happening on windows-gnu at all as it uses the .msi installer there.

Thanks for the recommendation, I'll look into using those.

**Comment by alexcrichton** [comment]
Ah sorry to clarify this was all on Windows, so in other words the x86_64-pc-windows-gnu installer. I guess that's a good question why it was using tar if it was supposed to use the msi...

Perhaps a bug?
