### ISSUE TITLE
msiexec returns 1639 with "help" popup

### ISSUE THREAD

**Issue by rusty-new-dev** [Diggsey/multirust-rs#33]
After trying many many many times to get multirust working on Windows without success (with msiexec returning 1639 over and over again with that confusing popup :sob:), I finally figured out why multirust was not working for me. std::process::Command will quote arguments as needed, except that the way it quote the arguments doesn't work for msiexec. When this:  

TARGETDIR=path with space

is given to std::process::Command, It turns it into:

"TARGETDIR=path with space"

but msiexec needs it as:

TARGETDIR="path with space"

Note the position of the double quotes. One workaround is to use MULTIRUST_HOME= to get multirust to use a path without spaces (and any other character that might get std::process::Command into quoting the TARGETDIR= argument). The other is to create a new user account with a folder that does not have any spaces (or characters that might get std::process::Command to quote TARGETDIR=).

PS: Having figured that out, I decided to use msys2 to try create an isolated environment to temporarily test multirust by setting MULTIRUST_HOME=/c/path/to/multirust/home , but that didn't work either ( since msys2 converts path in what they call "mixed mode", it ends up being c:/path/to/multirust/home instead of c:\path\to\multirust\home ). Of course, msiexec (like many Windows commands) barfed on this :sob:. Maybe multirust could change '/' to '\' in paths before passing them to msiexec (or maybe warn the user about it).I won't be surprised if there are other combinations that can make msiexec fail, but these are the only ones I've encountered so far. Sorry for the rant :stuck_out_tongue:.

**Comment by Diggsey** [comment]
Yes, this is an unfortunate consequence of the fact that rust chose to use posix semantics for command lines, while on windows command lines are a single string. The problem affects any programs which do not use CommandLineToArgvW or equivalent for parsing arguments.

Currently the only workaround is to ditch Command altogether and call CreateProcess directly, but I'll open an issue about adding an "unescaped arg" method.

**Comment by rusty-new-dev** [comment]
Another way around this issue might be to call MsiInstallProduct instead of running msiexec, but I guess there's no working msi-sys yet.

**Comment by Diggsey** [comment]
For reference the issue is https://github.com/rust-lang/rust/issues/29494

**Comment by retep998** [comment]
@Diggsey Would a working `msi-sys` with `MsiInstallProductW` be a functional alternative that can effectively fix this issue?

**Comment by Diggsey** [comment]
This is no longer hugely relevent, since with @brson's changes, multirust-rs no longer installs from the .msi installers. The installation logic is now intrinsic to multirust-rs, so it can just download the .tar.gz distributions!
