### ISSUE TITLE
'rustc' is an unknown command on Windows

### ISSUE THREAD

**Issue by alexcrichton** [Diggsey/multirust-rs#4]
Although `rustc.bat` is installed, it looks like in an MSYS shell at least running "rustc" as a command doesn't work.

```
bash: rustc: command not found
```

**Comment by Diggsey** [comment]
I'll get multirust-rs to output both shell script and batch file proxies on windows, that should fix the problem.

**Comment by alexcrichton** [comment]
Perhaps binaries could be emitted? This is actually also a problem on Unix where scripts are installed as `foo.sh` (and also aren't executable) which means that `rustc` also doesn't work there.

**Comment by alexcrichton** [comment]
(although shell scripts would work for Unix if they dropped the `.sh` and were made executable)

**Comment by Diggsey** [comment]
Reopened until I also mark them as executable.

**Comment by Diggsey** [comment]
OK, they should get marked as executable now.

**Comment by alexcrichton** [comment]
Thanks!
