### ISSUE TITLE
"multirust run" different syntax?

### ISSUE THREAD

**Issue by alexcrichton** [Diggsey/multirust-rs#5]
For example:

```
$ multirust run stable rustc -vV
thread '<main>' panicked at 'failed to run `stable`', ../src/libcore\option.rs:33
```

It looks like it's trying to interpret `stable` as the binary to run?

**Comment by Diggsey** [comment]
Ah, somewhere along the way I lost the `toolchain` parameter. I've fixed it now so `multirust run` will take that parameter, and `multirust proxy` will use the correct toolchain for the current directory.

**Comment by alexcrichton** [comment]
Thanks!
