### ISSUE TITLE
warning: multirust is installed but is not set up correctly: `rustc` invocations will not be proxied

### ISSUE THREAD

**Issue by DerGroncki** [Diggsey/multirust-rs#59]
Hi,

I need help to fix the following warning (terminal output):

>$ multirust list-toolchains
>warning: multirust is installed but is not set up correctly: `rustc` invocations will not be proxied.

>Ensure 'C:\Users\micha\AppData\Local\.multirust\bin' is on your PATH, and has priority.

>nightly

I am running Windows 10 pro.
My "Path" is correct.

I have installed: 
$ rustc --version
rustc 1.8.0-nightly (75271d8f1 2016-02-09)

$ cargo --version
cargo 0.9.0-nightly (3e285ce 2016-02-05)

How to setup multirust correctly?

Thanks.

Michael

**Comment by Diggsey** [comment]
Multirust has to be on your PATH before rustc/cargo if they are also on your PATH, otherwise it won't be able to intercept them correctly - that's what the warning is trying to tell you.

**Comment by DerGroncki** [comment]
Ok, thank you.

I think it is fixed now because

>$ multirust list-toolchains
>nightly

The warning is gone.

Thanks.

Michael
