### ISSUE TITLE
Can't reinstall toolchain after removing it

### ISSUE THREAD

**Issue by Eljay** [Diggsey/multirust-rs#7]
Steps to reproduce:
- `multirust default beta`
- `multirust remove-toolchain beta`
- `multirust default beta`

Output:
```
info: installing toolchain 'beta'
downloading file from: 'https://static.rust-lang.org/dist/channel-rust-beta.sha256'
downloading file from: 'https://static.rust-lang.org/dist/channel-rust-beta'
downloading file from: 'https://static.rust-lang.org/dist/rust-beta-x86_64-pc-windows-msvc.msi.sha256'
info: update hash matches: 1c393d0a66788a093712, skipping update...
info: default toolchain set to 'beta'
```

It doesn't actually reinstall the removed toolchain though, so attempts to use it result in:
```
error: not a directory: 'C:\Users\Lee\.multirust\toolchains\beta'
```

I was able to reinstall it by first deleting the beta file in update-hashes.

**Comment by Diggsey** [comment]
Thanks, from now on the update hash file should be removed at the same time a toolchain is uninstalled.
