### ISSUE TITLE
As a library, this has been a delight to use!

### ISSUE THREAD

**Issue by kamalmarhubi** [Diggsey/multirust-rs#72]
Not actually an issue!!

@Diggsey, @brson, and other authors: I've been using `multirust-rs` as a library in a little project which I've just wrapped up the initial version of ([rust-bisect](https://github.com/kamalmarhubi/rust-bisect)), and it's been a joy to use. It seems to expose all the things I want. Only minor changes were needed for as-a-library use, and they seemed welcome.

So I just wanted to say thanks and well done!

**Comment by brson** [comment]
Yay! I'm glad.

Beware there are probably lots of breaking changes in store still.

**Comment by Diggsey** [comment]
@kamalmarhubi Thanks! `rust-bisect` looks like a useful tool, I'm glad to see it was worthwhile separating out the library component.  (And sorry in advance for the imminent breakage :stuck_out_tongue_winking_eye: )

**Comment by kamalmarhubi** [comment]
You don't put non-master git deps in `Cargo.toml` without expecting some breakage!
